"""empty message

Revision ID: 7d5e4cdb7675
Revises: 
Create Date: 2020-10-13 14:20:02.734754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5e4cdb7675'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=40), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('coolers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=40), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('liquid', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=40), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('clockSpeed', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=40), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('VRAM', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hardDrives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=40), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('SSD', sa.Boolean(), nullable=False),
    sa.Column('gbSize', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('motherBoards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=40), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('networkCards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=40), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('powerSupplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=40), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('watts', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=40), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('gbSize', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('firstName', sa.String(length=40), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('caseId', sa.Integer(), nullable=True),
    sa.Column('motherBoardId', sa.Integer(), nullable=True),
    sa.Column('cpuId', sa.Integer(), nullable=True),
    sa.Column('coolerId', sa.Integer(), nullable=True),
    sa.Column('hardDriveId', sa.Integer(), nullable=True),
    sa.Column('ramId', sa.Integer(), nullable=True),
    sa.Column('gpuId', sa.Integer(), nullable=True),
    sa.Column('powerSupplyId', sa.Integer(), nullable=True),
    sa.Column('networkCardId', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caseId'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['coolerId'], ['coolers.id'], ),
    sa.ForeignKeyConstraint(['cpuId'], ['cpus.id'], ),
    sa.ForeignKeyConstraint(['gpuId'], ['gpus.id'], ),
    sa.ForeignKeyConstraint(['hardDriveId'], ['hardDrives.id'], ),
    sa.ForeignKeyConstraint(['motherBoardId'], ['motherBoards.id'], ),
    sa.ForeignKeyConstraint(['networkCardId'], ['networkCards.id'], ),
    sa.ForeignKeyConstraint(['powerSupplyId'], ['powerSupplies.id'], ),
    sa.ForeignKeyConstraint(['ramId'], ['ram.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('builds')
    op.drop_table('users')
    op.drop_table('ram')
    op.drop_table('powerSupplies')
    op.drop_table('networkCards')
    op.drop_table('motherBoards')
    op.drop_table('hardDrives')
    op.drop_table('gpus')
    op.drop_table('cpus')
    op.drop_table('coolers')
    op.drop_table('cases')
    # ### end Alembic commands ###
